run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gocyclo
    - dupl
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment"
    - "error strings should not be capitalized"
